development:
  adapter: postgresql
  encoding: unicode
  database: rubysocialclub_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rubysocialclub_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: rubysocialclub_production
  pool: 5
